#%RAML 1.0
title: Test API
mediaType:
- application/json

types:

  Parent:
    type: object
    discriminator: type
    properties:
      type: string

  Child1:
    type: Parent
    properties:
      value?: string
      value1: integer

  Child2:
    type: Parent
    discriminatorValue: child2
    properties:
      value?: string
      value2: integer

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Parent
