#%RAML 1.0
title: Test API
mediaType:
- application/json

types:

  Test:
    type: object
    properties:
      binary: file
      nullableBinary?: file

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test
