#%RAML 1.0
title: Test API
uses:
  lib: lib-decl-dups.raml
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
mediaType:
- application/json

types:

  Test:
    type: lib.Test
    properties:
      value2: string


/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test
