#%RAML 1.0 Library
uses:
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml

(sunday.kotlinModelPackage): io.test.client
(sunday.typeScriptModelModule): test/client

types:

  Test:
    type: object
    properties:
      value: string
