#%RAML 1.0
title: Test API
mediaType:
- application/json

types:

  Test:
    type: object
    properties:
      fromNilUnion: (string | nil)
      notRequired:
        required: false
        type: string

  Test2:
    type: object
    properties:
      optionalObject?: object
      nillableObject: object?
      optionalHierarchy?: Parent
      nillableHierarchy: Parent?

  Parent:
    type: object
    discriminator: type
    properties:
      type: string
      value: string

  Child1:
    type: Parent
    discriminatorValue: child1
    properties:
      type: string
      childValue: string

  Child2:
    type: Parent
    discriminatorValue: child2
    properties:
      type: string
      childValue: string

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body: Test | Test2
