#%RAML 1.0
title: Test API
uses:
  lib: lib-obj-inherits.raml
mediaType:
- application/json

types:

  Test2:
    type: lib.Test
    properties:
      value2: string

  Empty:
    type: Test2

  Test3:
    type: Empty
    properties:
      value3: string


/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test3
