#%RAML 1.0
title: Test API
mediaType:
- application/json

types:

  Test:
    type: object
    properties:
      some-value: string
      another_value: string

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body: Test
