#%RAML 1.0
title: Test API
uses:
  lib: lib-unions-uncommon-objects.raml
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
mediaType:
- application/json

(sunday.kotlinModelPackage): io.test.lib
(sunday.typeScriptModelModule): test/lib

types:

  Base:
    type: object
    properties:
      value: string

  Child1:
    type: Base
    properties:
      childValue: string

  Child2:
    type: lib.Base
    properties:
      childValue: string

  Test:
    type: object
    properties:
      value: (Child1 | Child2)

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test
