#%RAML 1.0
title: Test API
mediaType:
- application/json

types:

  Test:
    type: object
    properties:
      any: (integer | string)
      duplicate: (string | string)
      nullable: (string | nil)

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test
