#%RAML 1.0
title: External Discriminator No Variants Regression
uses:
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
mediaType:
- application/json

types:
  Payload:
    (sunday.externallyDiscriminated): true
    type: object
    properties:
      value?: string

  Container:
    type: object
    properties:
      payload:
        type: Payload
        (sunday.externalDiscriminator): payloadType
      payloadType: string

/tests:
  get:
    responses:
      200:
        body:
          type: Container
