#%RAML 1.0
title: Shared Nested Type Linking Regression
uses:
  sun: https://outfoxx.github.io/sunday-generator/sunday.raml
  lib: shared-nested-type-linking-lib.raml
mediaType:
- application/json

types:
  Wrapper:
    type: object
    properties:
      params: lib.MessageSendParams
      message?: lib.Message

/tests:
  get:
    responses:
      200:
        body:
          type: Wrapper
