#%RAML 1.0
title: Test API
uses:
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
mediaType:
- application/json

(sunday.kotlinPackage): io.explicit.test
(sunday.kotlinPackage:client): io.explicit.test.client

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: object
          properties:
            value: string
