#%RAML 1.0
title: Test API
uses:
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
  lib: lib-type-nested-3.raml
mediaType:
- application/json

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: lib.GroupMember
