#%RAML 1.0
title: Test API
uses:
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
mediaType:
- application/json

(sunday.javaModelPackage): io.explicit.test
(sunday.javaModelPackage:server): io.explicit.test.server

types:

  Test:
    type: object
    properties:
      value:
        type: string

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test
