#%RAML 1.0
title: Test API
uses:
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
mediaType:
- application/json

types:

  Value:
    type: string
    (sunday.kotlinType): java.time.LocalDateTime
    (sunday.kotlinType:server): java.time.Instant

  Test:
    type: object
    properties:
      value: Value

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test
