#%RAML 1.0 Overlay
extends: test.raml

annotationTypes:
  test-overlay-ann: boolean

types:

  Tester:
    (test-overlay-ann): true

/test/{id}:
  (test-overlay-ann): true
  get:
    (test-overlay-ann): true
