openapi: 3.1.0
info: {title: Native client, version: 1.0.0}
servers:
  - url: http://{host}/api
    variables:
      host: {default: '${fixture.idp.authority}'}
x-sunday-quarkus-config:
  client:
    properties:
      quarkus.rest-client-oidc-filter.refresh-on-unauthorized: true
      quarkus.rest-client."io.test.packaged.client.API".read-timeout: 1000
      quarkus.rest-client."io.test.packaged.client.API".connect-timeout: 1000
      quarkus.rest-client."io.test.packaged.client.API".max-redirects: 1
components:
  securitySchemes:
    service:
      type: http
      scheme: bearer
      x-sunday-security:
        client:
          provider: service
          flow: clientCredentials
          quarkus:
            mode: acquire
            properties:
              token-path: ${fixture.idp.url}/token
              discovery-enabled: false
              refresh-token-time-skew: 8S
    user:
      type: http
      scheme: bearer
      x-sunday-security:
        client:
          provider: incoming
          flow: external
          quarkus: {mode: propagate}
    exchange:
      type: http
      scheme: bearer
      x-sunday-security:
        client:
          provider: exchange
          flow: external
          quarkus:
            mode: exchange
            properties:
              token-path: ${fixture.idp.url}/token
              discovery-enabled: false
paths:
  /write:
    get:
      operationId: writeCall
      security: [{service: [write]}]
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: {type: string}
  /service:
    get:
      operationId: serviceCall
      security: [{service: [read]}]
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: {type: string}
  /user:
    get:
      operationId: userCall
      security: [{user: []}]
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: {type: string}
  /exchange:
    get:
      operationId: exchangeCall
      security: [{exchange: []}]
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: {type: string}
  /public:
    get:
      operationId: publicCall
      security: []
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: {type: string}
  /reject-get:
    get:
      operationId: rejectedGet
      security: [{service: [read]}]
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: {type: string}
  /reject-post:
    post:
      operationId: rejectedPost
      security: [{service: [read]}]
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: {type: string}
