#%RAML 1.0
title: Test API
mediaType:
- application/json

types:

  TestEnum:
    enum: [none, some, all, snake_case, kebab-case, invalid:char]

  Test:
    type: object
    properties:
      enumVal:
        type: TestEnum
      setVal:
        type: array
        uniqueItems: true
        items: TestEnum
      arrayVal:
        type: array
        uniqueItems: false
        items: TestEnum

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test
