#%RAML 1.0
title: Test API
mediaType:
- application/json

types:

  Test:
    type: object
    properties:
      float:
        type: number
        format: float
      double:
        type: number
        format: double
      none:
        type: number

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test
