#%RAML 1.0
title: Test API
uses:
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
mediaType:
- application/json

types:

  Test:
    type: object
    properties:
      byteMin:
        type: integer
        format: int8
        minimum: 1
      byteMax:
        type: integer
        format: int8
        maximum: 2
      byteMultiple:
        type: integer
        format: int8
        multipleOf: 3
      shortMin:
        type: integer
        format: int16
        minimum: 4
      shortMax:
        type: integer
        format: int16
        maximum: 5
      shortMultiple:
        type: integer
        format: int16
        multipleOf: 6
      intMin:
        type: integer
        format: int32
        minimum: 7
      intMax:
        type: integer
        format: int32
        maximum: 8
      intMultiple:
        type: integer
        format: int32
        multipleOf: 9
      longMin:
        type: integer
        format: int64
        minimum: 10
      longMax:
        type: integer
        format: int64
        maximum: 11
      longMultiple:
        type: integer
        format: int64
        multipleOf: 12

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test
