#%RAML 1.0
title: Test API
mediaType:
- application/json

types:

  Test:
    type: object
    properties:
      codes:
        type: array
        items:
          type: string
          minLength: 2
          maxLength: 5
          pattern: "^[A-Z]+$"

/tests/{id}:

  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test
