#%RAML 1.0
title: Test API
uses:
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
mediaType:
- application/json

(sunday.problemTypes):

  test_not_found:
    status: 404
    title: Test Not Found
    detail: The requested test was not found

  another_not_found:
    status: 404
    title: Test Not Found
    detail: The requested test was not found

types:

  Test:
    type: object
    properties:
      value: string


/test1:
  get:
    displayName: fetchTest1
    queryParameters:
      limit: integer
    (sunday.problems): [test_not_found, another_not_found]
    (sunday.nullify): [test_not_found, another_not_found, 404, 405]
    responses:
      200:
        body: Test

/test2:
  get:
    displayName: fetchTest2
    queryParameters:
      limit: integer
    (sunday.problems): [test_not_found, another_not_found]
    (sunday.nullify): [test_not_found, another_not_found, 404]
    responses:
      200:
        body: Test

/test3:
  get:
    displayName: fetchTest3
    queryParameters:
      limit: integer
    (sunday.problems): [test_not_found, another_not_found]
    (sunday.nullify): [test_not_found, another_not_found]
    responses:
      200:
        body: Test

/test4:
  get:
    displayName: fetchTest4
    queryParameters:
      limit: integer
    (sunday.nullify): [404, 405]
    responses:
      200:
        body: Test

/test5:
  get:
    displayName: fetchTest5
    queryParameters:
      limit: integer
    (sunday.nullify): [404]
    responses:
      200:
        body: Test
