#%RAML 1.0
title: Test API
mediaType:
- application/json

types:

  Test:
    type: object
    properties:
      value1: string
      value2: integer


/tests/{obj}/{str}/{int}/{def}:
  uriParameters:
    obj?: Test
    str?: string
    int: integer | nil
  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: Test
