#%RAML 1.0
title: Test API
mediaType:
- application/json

types:

  Test:
    type: object
    properties:
      value1: string
      value2: integer


/tests:
  get:
    displayName: fetchTest
    headers:
      obj: Test
      str-req: string
      int:
        type: integer
        default: 5
    responses:
      200:
        body:
          type: Test
  delete: # ensure headers are not included in following methods
    displayName: deleteTest
    responses:
      204: