#%RAML 1.0
title: Test API
uses:
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
mediaType:
- application/json

types:

  Test:
    type: object
    properties:
      value: string


/tests:
  get:
    displayName: fetchEvents
    (sunday.sse): true
    responses:
      200:
        body: Test

/tests/server:
  get:
    displayName: fetchEventsServer
    (sunday.sse:server): true
    responses:
      200:
        body: Test


/tests/client:
  get:
    displayName: fetchEventsClient
    (sunday.sse:client): true
    responses:
      200:
        body: Test

