#%RAML 1.0
title: Test API
uses:
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
mediaType:
- application/json

types:

  Base:
    type: object
    discriminator: type
    properties:
      type: string
      value: string

  Test1:
    type: Base
    properties:
      value1: string

  Test2:
    type: Base
    properties:
      value2: string

/test1:
  get:
    displayName: fetchEventsSimple
    (sunday.eventStream): simple
    responses:
      200:
        body:
          application/json:
            type: Base
/test2:
  get:
    displayName: fetchEventsDiscriminated
    (sunday.eventStream): discriminated
    responses:
      200:
        body:
          application/json:
            type: Test1 | Test2
