#%RAML 1.0
title: Test API
uses:
  sunday: https://outfoxx.github.io/sunday-generator/sunday.raml
mediaType:
- application/json

types:

  Test1:
    type: object
    properties:
      value: string

  Test2:
    type: object
    discriminatorValue: test2
    properties:
      value: string

  Test3:
    type: object
    discriminatorValue: t3
    properties:
      value: string

/tests:
  get:
    displayName: fetchEvents
    (sunday.eventStream): discriminated
    responses:
      200:
        body:
          text/event-stream:
            type: Test1 | Test2 | Test3
