#%RAML 1.0
title: Test API
mediaType:
- application/json

types:

  Test:
    type: object
    properties:
      value: string

  Base:
    type: object
    discriminator: type
    properties:
      type: string

  Derived:
    type: Base
    discriminatorValue: derived
    properties:
      value: string

/tests:
  get:
    displayName: fetchTest
    responses:
      200:
        body: Test

/tests/derived:
  get:
    displayName: fetchDerivedTest
    responses:
      200:
        body: Base
