quarkus.http.test-port=0
quarkus.devservices.enabled=false
quarkus.http.auth.proactive=false
quarkus.oidc.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtev3sDagxpCBQtJ1coLmvReUm0eJGTa8aQuCH5FEQxDhHPCKYdEmBEfnso6wiZE3IRhpnFBAfQul0RbZ28WNvdiGO5Jx4sZ8kG7/RNHO7sJ9zrHIUcJ9cJ1/+HqIo9aw4oFPPBvnOD9j+EYj/YXcWl15/Tdm0QZBlfeT8cS8SHlH3IvbWFcvt6UsVknkUp5V/QMRLEC8JY6qr2Q6Zay2tPA1JQoQw9t7cVKZ2rZoyDB5sXSJNfV7TQnoDB8GLDCfG/sdnzzhXV2Kd9XWciQqH1Y1bKv+J+6NMOAneNWRhvv0Pf5tpYU2VNM/A0apj/3dqNBNfQ9SZSctGn2Yb5RxZwIDAQAB



# Intentional override of generated library defaults, exercised by the packaged test.
quarkus.rest-client."io.test.packaged.client.API".connect-timeout=2000
