// Generated by dts-bundle-generator v9.5.1

import { Duration as JsJodaDuration, Instant as JsJodaInstant, LocalDate as JsJodaLocalDate, LocalDateTime as JsJodaLocalDateTime, LocalTime as JsJodaLocalTime, OffsetDateTime as JsJodaOffsetDateTime, OffsetTime as JsJodaOffsetTime, Period as JsJodaPeriod, ZoneId as JsJodaZoneId, ZoneOffset as JsJodaZoneOffset, ZonedDateTime as JsJodaZonedDateTime } from '@js-joda/core';
import { z } from 'zod';

export declare class MediaType {
	type: MediaType.Type;
	tree: MediaType.Tree;
	subtype: string;
	suffix?: MediaType.Suffix;
	parameters: Record<string, string>;
	constructor(params: {
		type: MediaType.Type;
		tree?: MediaType.Tree;
		subtype: string;
		suffix?: MediaType.Suffix;
		parameters?: Record<string, string>;
	});
	parameter(name: MediaType.ParameterName | string): string | undefined;
	with(params: {
		type?: MediaType.Type;
		tree?: MediaType.Tree;
		subtype?: string;
		suffix?: MediaType.Suffix;
		parameters?: Record<string, string>;
	}): MediaType;
	withParameter(parameter: MediaType.ParameterName | string, value: string): MediaType;
	get value(): string;
	compatible(other: MediaType): boolean;
	equals(other: MediaType): boolean;
	toString(): string;
}
export declare namespace MediaType {
	enum Type {
		Application = "application",
		Audio = "audio",
		Example = "example",
		Font = "font",
		Image = "image",
		Message = "message",
		Model = "model",
		Multipart = "multipart",
		Text = "text",
		Video = "video",
		Any = "*"
	}
	namespace Type {
		function from(value: string): Type | undefined;
	}
	enum Tree {
		Standard = "",
		Vendor = "vnd.",
		Personal = "prs.",
		Unregistered = "x.",
		Obsolete = "x-",
		Any = "*"
	}
	namespace Tree {
		function from(value: string): Tree | undefined;
	}
	enum Suffix {
		XML = "xml",
		JSON = "json",
		BER = "ber",
		DER = "der",
		FastInfoSet = "fastinfoset",
		WBXML = "wbxml",
		Zip = "zip",
		CBOR = "cbor"
	}
	namespace Suffix {
		function from(value: string): Suffix | undefined;
	}
	enum ParameterName {
		CharSet = "charset"
	}
	function from(value?: string | null): MediaType;
	function from(value: string | null | undefined, def: MediaType): MediaType;
	const Plain: MediaType;
	const HTML: MediaType;
	const JSON: MediaType;
	const YAML: MediaType;
	const CBOR: MediaType;
	const EventStream: MediaType;
	const OctetStream: MediaType;
	const WWWFormUrlEncoded: MediaType;
	const X509CACert: MediaType;
	const X509UserCert: MediaType;
	const Any: MediaType;
	const AnyText: MediaType;
	const AnyImage: MediaType;
	const AnyAudio: MediaType;
	const AnyVideo: MediaType;
	const JSONStructured: MediaType;
	const XMLStructured: MediaType;
	const Problem: MediaType;
	const JsonPatch: MediaType;
	const MergePatch: MediaType;
}
export type SchemaFormat = "json" | "cbor";
declare enum DateEncoding {
	DECIMAL_SECONDS_SINCE_EPOCH = 0,
	MILLISECONDS_SINCE_EPOCH = 1,
	ISO8601 = 2
}
declare enum NumericDateDecoding {
	DECIMAL_SECONDS_SINCE_EPOCH = 0,
	MILLISECONDS_SINCE_EPOCH = 1
}
declare enum ArrayBufferEncoding {
	BASE64 = 0,
	BASE64URL = 1,
	RAW_BYTES = 2
}
export interface SchemaPolicy {
	format: SchemaFormat;
	dateEncoding: DateEncoding;
	numericDateDecoding: NumericDateDecoding;
	arrayBufferEncoding: ArrayBufferEncoding;
}
declare const SchemaDefType: unique symbol;
export type AnySchema = z.ZodType;
export type SchemaDef<S extends AnySchema = AnySchema> = {
	readonly id: symbol;
	readonly build: (runtime: SchemaRuntime) => S;
	readonly debugName?: string;
	readonly [SchemaDefType]: true;
};
export type SchemaLike<Output = unknown, Input = unknown> = z.ZodType<Output, Input> | SchemaDef<z.ZodType<Output, Input>>;
export type ResolvedSchema<S> = S extends SchemaDef<infer TSchema> ? TSchema : S extends AnySchema ? S : never;
export type SchemaInput<S extends SchemaLike> = z.input<ResolvedSchema<S>>;
export type SchemaOutput<S extends SchemaLike> = z.output<ResolvedSchema<S>>;
export declare function defineSchema<S extends AnySchema>(builder: (runtime: SchemaRuntime) => S, options?: {
	id?: symbol;
	debugName?: string;
}): SchemaDef<S>;
export interface SchemaRuntime {
	readonly policy: SchemaPolicy;
	resolveSchema<S extends SchemaLike>(ref: S): ResolvedSchema<S>;
}
export interface Problem {
	type: URL;
	title: string;
	status: number;
	detail?: string;
	instance?: URL;
	[key: string]: unknown;
}
export declare const ProblemWireSchema: z.ZodObject<{
	type: z.ZodOptional<z.ZodUnion<readonly [
		z.ZodString,
		z.ZodCustom<URL, URL>
	]>>;
	title: z.ZodString;
	status: z.ZodNumber;
	detail: z.ZodOptional<z.ZodString>;
	instance: z.ZodOptional<z.ZodUnion<readonly [
		z.ZodString,
		z.ZodCustom<URL, URL>
	]>>;
}, z.core.$loose>;
export type ProblemSpec = z.infer<typeof ProblemWireSchema>;
export declare class Problem extends Error implements Problem {
	static BLANK_URL: URL;
	type: URL;
	title: string;
	status: number;
	detail?: string;
	instance?: URL;
	private _parameters?;
	get parameters(): Record<string, unknown> | undefined;
	constructor(spec: ProblemSpec);
	toString(): string;
	static fromStatus(status: number, title: string): Problem;
	static fromResponse(response: Response): Promise<Problem>;
	private static parseURL;
}
export declare function createProblemCodec<TProblem extends Problem, TWire extends z.infer<typeof ProblemWireSchema>>(problemType: new (spec: TWire) => TProblem, wireSchema: z.ZodType<TWire>): z.ZodType<TProblem>;
export type ProblemMatcher = z.ZodType<Problem> | ((problem: Problem) => boolean);
export declare function nullifyProblem<T>(promise: Promise<T>, statuses: number[], problemTypes: ProblemMatcher[]): Promise<T | null>;
export interface MediaTypeDecoder {
	decode<T>(response: Response, type: SchemaLike<T>): Promise<T>;
}
export interface TextMediaTypeDecoder extends MediaTypeDecoder {
	decodeText<T>(text: string, type: SchemaLike<T>): T;
}
export interface ResponseHeaderEntry {
	readonly name: string;
	readonly value: string;
}
export declare class ResponseHeaders {
	readonly entries: readonly ResponseHeaderEntry[];
	constructor(entries: readonly ResponseHeaderEntry[]);
	static from(headers: Headers): ResponseHeaders;
	getAll(name: string): readonly string[];
	get(name: string): string | undefined;
	get contentType(): MediaType | undefined;
}
export declare class OperationResponse<R> {
	readonly result: R;
	readonly transportResponse: Response;
	readonly status: number;
	readonly headers: ResponseHeaders;
	constructor(result: R, transportResponse: Response);
	getHeaders(name: string): readonly string[];
	getHeader(name: string): string | undefined;
	get contentType(): MediaType | undefined;
}
export declare class URLTemplate {
	template: string;
	parameters: Record<string, unknown>;
	constructor(template: string, parameters?: Record<string, unknown>);
	complete(relativeTemplate: string, parameters: Record<string, unknown>): URL;
}
export interface Logger {
	trace?(...data: unknown[]): void;
	debug?(...data: unknown[]): void;
	info?(...data: unknown[]): void;
	log?(...data: unknown[]): void;
	warn?(...data: unknown[]): void;
	error?(...data: unknown[]): void;
}
export type TransportRequest<Factory> = Factory extends Transport<infer NativeRequest> ? NativeRequest : never;
export interface BuildRequestOptions {
	readonly signal?: AbortSignal;
}
export interface ExecuteOptions {
	readonly signal?: AbortSignal;
}
export interface OperationSpec<RequestBody, ResponseBody> {
	readonly request: RequestSpec<RequestBody>;
	readonly responseType?: SchemaLike<ResponseBody>;
}
export interface VoidOperationSpec<RequestBody = void> extends OperationSpec<RequestBody, void> {
	readonly responseType?: undefined;
}
export interface TypedOperationSpec<RequestBody, ResponseBody> extends OperationSpec<RequestBody, ResponseBody> {
	readonly responseType: SchemaLike<ResponseBody>;
}
export interface Operation<RequestBody, ResponseBody, Factory extends Transport<unknown> = Transport> {
	readonly spec: OperationSpec<RequestBody, ResponseBody>;
	execute(options?: ExecuteOptions): Promise<ResponseBody>;
	response(options?: ExecuteOptions): Promise<OperationResponse<ResponseBody>>;
	transportRequest(options?: BuildRequestOptions): Promise<TransportRequest<Factory>>;
	transportResponse(options?: ExecuteOptions): Promise<Response>;
}
export interface NullifySpec {
	readonly statuses: readonly number[];
	readonly problemTypes: readonly ProblemMatcher[];
}
export interface NullableOperation<RequestBody, ResponseBody, Factory extends Transport<unknown> = Transport> extends Operation<RequestBody, ResponseBody, Factory> {
	readonly nullify: NullifySpec;
	executeOrNull(options?: ExecuteOptions): Promise<ResponseBody | null>;
}
export declare function createOperation<RequestBody = void, ResponseBody = void, Factory extends Transport<unknown> = Transport>(transport: Factory, spec: TypedOperationSpec<RequestBody, ResponseBody>): Operation<RequestBody, ResponseBody, Factory>;
export declare function createOperation<RequestBody = void, Factory extends Transport<unknown> = Transport>(transport: Factory, spec: VoidOperationSpec<RequestBody>): Operation<RequestBody, void, Factory>;
export declare function createNullableOperation<RequestBody = void, ResponseBody = void, Factory extends Transport<unknown> = Transport>(transport: Factory, spec: TypedOperationSpec<RequestBody, ResponseBody>, nullify: NullifySpec): NullableOperation<RequestBody, ResponseBody, Factory>;
export declare function createNullableOperation<RequestBody = void, Factory extends Transport<unknown> = Transport>(transport: Factory, spec: VoidOperationSpec<RequestBody>, nullify: NullifySpec): NullableOperation<RequestBody, void, Factory>;
export interface Transport<NativeRequest = Request> {
	readonly baseUrl: URLTemplate;
	registerProblem(type: URL | string, problemType: SchemaLike<Problem>): void;
	transportRequest(requestSpec: RequestSpec<unknown>): Promise<NativeRequest>;
	transportResponse(request: NativeRequest, dataExpected?: boolean): Promise<Response>;
	transportResponse<B>(requestSpec: RequestSpec<B>, dataExpected?: boolean): Promise<Response>;
	response<B, R>(requestSpec: RequestSpec<B>, resultType: SchemaLike<R>): Promise<OperationResponse<R>>;
	response<B>(requestSpec: RequestSpec<B>): Promise<OperationResponse<void>>;
	result<B, R>(requestSpec: RequestSpec<B>, resultType: SchemaLike<R>): Promise<R>;
	result<B>(requestSpec: RequestSpec<B>): Promise<void>;
	eventSource(requestSpec: RequestSpec<void>): ExtEventSource;
	eventStream<E>(requestSpec: RequestSpec<void>, decoder: (decoder: TextMediaTypeDecoder, event: string | undefined, id: string | undefined, data: string, logger?: Logger) => E | undefined): AsyncIterable<E>;
}
export interface ExtEventSource extends EventSource {
	connect(): void;
}
export type RequestMethod = "GET" | "PUT" | "POST" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";
export interface RequestSpec<B> {
	method: RequestMethod;
	pathTemplate: string;
	pathParameters?: Record<string, unknown>;
	queryParameters?: Record<string, unknown>;
	body?: B;
	bodyType?: SchemaLike<B>;
	contentTypes?: MediaType[];
	acceptTypes?: MediaType[];
	headers?: Record<string, unknown>;
	signal?: AbortSignal;
}
export declare const UnknownSchema: z.ZodUnknown;
export declare const NullSchema: z.ZodNull;
export declare const StringSchema: z.ZodString;
export declare const NumberSchema: z.ZodNumber;
export declare const BooleanSchema: z.ZodBoolean;
export declare const URLSchema: SchemaDef<z.ZodType<URL, unknown, z.core.$ZodTypeInternals<URL, unknown>>>;
export declare const ArrayBufferSchema: SchemaDef<z.ZodType<ArrayBuffer, unknown, z.core.$ZodTypeInternals<ArrayBuffer, unknown>>>;
export type Instant = JsJodaInstant;
export type LocalDate = JsJodaLocalDate;
export type LocalTime = JsJodaLocalTime;
export type LocalDateTime = JsJodaLocalDateTime;
export type OffsetTime = JsJodaOffsetTime;
export type OffsetDateTime = JsJodaOffsetDateTime;
export type ZonedDateTime = JsJodaZonedDateTime;
export type Duration = JsJodaDuration;
export type Period = JsJodaPeriod;
export type ZoneId = JsJodaZoneId;
export type ZoneOffset = JsJodaZoneOffset;
export declare const Instant: typeof JsJodaInstant;
export declare const LocalDate: typeof JsJodaLocalDate;
export declare const LocalTime: typeof JsJodaLocalTime;
export declare const LocalDateTime: typeof JsJodaLocalDateTime;
export declare const OffsetTime: typeof JsJodaOffsetTime;
export declare const OffsetDateTime: typeof JsJodaOffsetDateTime;
export declare const ZonedDateTime: typeof JsJodaZonedDateTime;
export declare const Duration: typeof JsJodaDuration;
export declare const Period: typeof JsJodaPeriod;
export declare const ZoneId: typeof JsJodaZoneId;
export declare const ZoneOffset: typeof JsJodaZoneOffset;
export declare const DateSchema: SchemaDef<z.ZodType<Date, unknown, z.core.$ZodTypeInternals<Date, unknown>>>;
export declare const InstantSchema: SchemaDef<z.ZodType<JsJodaInstant, unknown, z.core.$ZodTypeInternals<JsJodaInstant, unknown>>>;
export declare const ZonedDateTimeSchema: SchemaDef<z.ZodType<JsJodaZonedDateTime, unknown, z.core.$ZodTypeInternals<JsJodaZonedDateTime, unknown>>>;
export declare const OffsetDateTimeSchema: SchemaDef<z.ZodType<JsJodaOffsetDateTime, unknown, z.core.$ZodTypeInternals<JsJodaOffsetDateTime, unknown>>>;
export declare const OffsetTimeSchema: SchemaDef<z.ZodType<JsJodaOffsetTime, unknown, z.core.$ZodTypeInternals<JsJodaOffsetTime, unknown>>>;
export declare const LocalDateTimeSchema: SchemaDef<z.ZodType<JsJodaLocalDateTime, unknown, z.core.$ZodTypeInternals<JsJodaLocalDateTime, unknown>>>;
export declare const LocalDateSchema: SchemaDef<z.ZodType<JsJodaLocalDate, unknown, z.core.$ZodTypeInternals<JsJodaLocalDate, unknown>>>;
export declare const LocalTimeSchema: SchemaDef<z.ZodType<JsJodaLocalTime, unknown, z.core.$ZodTypeInternals<JsJodaLocalTime, unknown>>>;
export declare const DurationSchema: SchemaDef<z.ZodType<JsJodaDuration, unknown, z.core.$ZodTypeInternals<JsJodaDuration, unknown>>>;

export {};
