name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:

  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checks
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk11-build-test
        arguments: check -x test


  build-test-tools:
    runs-on: ubuntu-latest

    needs: [check]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: oracle

    - name: Build & Test
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk11-build-test
        arguments: cleanTest :cli:test :gradle-plugin:test

    - name: Report Tests
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Tests Results (Tools)
        path: "**/build/test-results/*/*.xml"
        reporter: java-junit


  build-test-swift:
    runs-on: macos-12

    needs: [check]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: oracle

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer

    - name: Build & Test
      run: ./gradlew cleanTest :generator:test --tests "io.outfoxx.sunday.generator.swift.*"

    - name: Report Tests
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Tests Results (Swift)
        path: "generator/build/test-results/*/*.xml"
        reporter: java-junit


  build-test-typescript:
    runs-on: ubuntu-latest

    needs: [check]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: oracle

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build & Test
      run: ./gradlew cleanTest :generator:test --tests "io.outfoxx.sunday.generator.typescript.*"

    - name: Report Tests
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Tests Results (TypeScript)
        path: "generator/build/test-results/*/*.xml"
        reporter: java-junit


  build-test-kotlin:
    runs-on: ubuntu-latest

    needs: [check]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: oracle

    - name: Build & Test
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk11-build-test
        arguments: cleanTest :generator:test --tests "io.outfoxx.sunday.generator.kotlin.*"

    - name: Report Tests
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Tests Results (Kotlin)
        path: "generator/build/test-results/*/*.xml"
        reporter: java-junit

  report:
    runs-on: ubuntu-latest

    needs: [check, build-test-tools, build-test-swift, build-test-kotlin, build-test-typescript]

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Report SonarCloud
      uses: burrunan/gradle-cache-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        job-id: jdk11-build-test
        arguments: check sonar -x test
