name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build Docs
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk8-build-test
        arguments: dokkaHtmlMultiModule

    - name: Publish Maven
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk8-build-test
        arguments: build publish -x test
        properties: |
          github.user=${GITHUB_ACTOR}
          github.token=${{ secrets.GITHUB_TOKEN }}

    - name: Publish Docker
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk8-build-test
        arguments: build jib -x test
        properties: |
          github.user=${GITHUB_ACTOR}
          github.token=${{ secrets.GITHUB_TOKEN }}

    - name: Publish Documentation
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        clean: false
        folder: build/dokka/
